# Generated by Django 2.2.2 on 2019-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('key_word', models.CharField(max_length=255)),
                ('job_place', models.CharField(max_length=255)),
                ('job_experience', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('financing', models.CharField(max_length=255)),
                ('scale', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('wage', models.CharField(max_length=255)),
                ('job_duty', models.CharField(max_length=255)),
                ('job_benefits', models.CharField(max_length=255)),
                ('job_describe', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'job',
                'managed': True,
            },
        ),
    ]
